/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corecssapcomv1alpha1 "github.com/sap/component-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BlueprintLister helps list Blueprints.
// All objects returned here must be treated as read-only.
type BlueprintLister interface {
	// List lists all Blueprints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corecssapcomv1alpha1.Blueprint, err error)
	// Blueprints returns an object that can list and get Blueprints.
	Blueprints(namespace string) BlueprintNamespaceLister
	BlueprintListerExpansion
}

// blueprintLister implements the BlueprintLister interface.
type blueprintLister struct {
	listers.ResourceIndexer[*corecssapcomv1alpha1.Blueprint]
}

// NewBlueprintLister returns a new BlueprintLister.
func NewBlueprintLister(indexer cache.Indexer) BlueprintLister {
	return &blueprintLister{listers.New[*corecssapcomv1alpha1.Blueprint](indexer, corecssapcomv1alpha1.Resource("blueprint"))}
}

// Blueprints returns an object that can list and get Blueprints.
func (s *blueprintLister) Blueprints(namespace string) BlueprintNamespaceLister {
	return blueprintNamespaceLister{listers.NewNamespaced[*corecssapcomv1alpha1.Blueprint](s.ResourceIndexer, namespace)}
}

// BlueprintNamespaceLister helps list and get Blueprints.
// All objects returned here must be treated as read-only.
type BlueprintNamespaceLister interface {
	// List lists all Blueprints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corecssapcomv1alpha1.Blueprint, err error)
	// Get retrieves the Blueprint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corecssapcomv1alpha1.Blueprint, error)
	BlueprintNamespaceListerExpansion
}

// blueprintNamespaceLister implements the BlueprintNamespaceLister
// interface.
type blueprintNamespaceLister struct {
	listers.ResourceIndexer[*corecssapcomv1alpha1.Blueprint]
}
