/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corecssapcomv1alpha1 "github.com/sap/component-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BlueprintVersionLister helps list BlueprintVersions.
// All objects returned here must be treated as read-only.
type BlueprintVersionLister interface {
	// List lists all BlueprintVersions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corecssapcomv1alpha1.BlueprintVersion, err error)
	// BlueprintVersions returns an object that can list and get BlueprintVersions.
	BlueprintVersions(namespace string) BlueprintVersionNamespaceLister
	BlueprintVersionListerExpansion
}

// blueprintVersionLister implements the BlueprintVersionLister interface.
type blueprintVersionLister struct {
	listers.ResourceIndexer[*corecssapcomv1alpha1.BlueprintVersion]
}

// NewBlueprintVersionLister returns a new BlueprintVersionLister.
func NewBlueprintVersionLister(indexer cache.Indexer) BlueprintVersionLister {
	return &blueprintVersionLister{listers.New[*corecssapcomv1alpha1.BlueprintVersion](indexer, corecssapcomv1alpha1.Resource("blueprintversion"))}
}

// BlueprintVersions returns an object that can list and get BlueprintVersions.
func (s *blueprintVersionLister) BlueprintVersions(namespace string) BlueprintVersionNamespaceLister {
	return blueprintVersionNamespaceLister{listers.NewNamespaced[*corecssapcomv1alpha1.BlueprintVersion](s.ResourceIndexer, namespace)}
}

// BlueprintVersionNamespaceLister helps list and get BlueprintVersions.
// All objects returned here must be treated as read-only.
type BlueprintVersionNamespaceLister interface {
	// List lists all BlueprintVersions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corecssapcomv1alpha1.BlueprintVersion, err error)
	// Get retrieves the BlueprintVersion from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corecssapcomv1alpha1.BlueprintVersion, error)
	BlueprintVersionNamespaceListerExpansion
}

// blueprintVersionNamespaceLister implements the BlueprintVersionNamespaceLister
// interface.
type blueprintVersionNamespaceLister struct {
	listers.ResourceIndexer[*corecssapcomv1alpha1.BlueprintVersion]
}
