/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BlueprintListerExpansion allows custom methods to be added to
// BlueprintLister.
type BlueprintListerExpansion interface{}

// BlueprintNamespaceListerExpansion allows custom methods to be added to
// BlueprintNamespaceLister.
type BlueprintNamespaceListerExpansion interface{}

// BlueprintVersionListerExpansion allows custom methods to be added to
// BlueprintVersionLister.
type BlueprintVersionListerExpansion interface{}

// BlueprintVersionNamespaceListerExpansion allows custom methods to be added to
// BlueprintVersionNamespaceLister.
type BlueprintVersionNamespaceListerExpansion interface{}

// ComponentListerExpansion allows custom methods to be added to
// ComponentLister.
type ComponentListerExpansion interface{}

// ComponentNamespaceListerExpansion allows custom methods to be added to
// ComponentNamespaceLister.
type ComponentNamespaceListerExpansion interface{}
