/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/component-operator/api/v1alpha1"
	corecssapcomv1alpha1 "github.com/sap/component-operator/pkg/client/clientset/versioned/typed/core.cs.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeComponents implements ComponentInterface
type fakeComponents struct {
	*gentype.FakeClientWithList[*v1alpha1.Component, *v1alpha1.ComponentList]
	Fake *FakeCoreV1alpha1
}

func newFakeComponents(fake *FakeCoreV1alpha1, namespace string) corecssapcomv1alpha1.ComponentInterface {
	return &fakeComponents{
		gentype.NewFakeClientWithList[*v1alpha1.Component, *v1alpha1.ComponentList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("components"),
			v1alpha1.SchemeGroupVersion.WithKind("Component"),
			func() *v1alpha1.Component { return &v1alpha1.Component{} },
			func() *v1alpha1.ComponentList { return &v1alpha1.ComponentList{} },
			func(dst, src *v1alpha1.ComponentList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ComponentList) []*v1alpha1.Component { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ComponentList, items []*v1alpha1.Component) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
