/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/component-operator/api/v1alpha1"
	corecssapcomv1alpha1 "github.com/sap/component-operator/pkg/client/clientset/versioned/typed/core.cs.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBlueprints implements BlueprintInterface
type fakeBlueprints struct {
	*gentype.FakeClientWithList[*v1alpha1.Blueprint, *v1alpha1.BlueprintList]
	Fake *FakeCoreV1alpha1
}

func newFakeBlueprints(fake *FakeCoreV1alpha1, namespace string) corecssapcomv1alpha1.BlueprintInterface {
	return &fakeBlueprints{
		gentype.NewFakeClientWithList[*v1alpha1.Blueprint, *v1alpha1.BlueprintList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("blueprints"),
			v1alpha1.SchemeGroupVersion.WithKind("Blueprint"),
			func() *v1alpha1.Blueprint { return &v1alpha1.Blueprint{} },
			func() *v1alpha1.BlueprintList { return &v1alpha1.BlueprintList{} },
			func(dst, src *v1alpha1.BlueprintList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BlueprintList) []*v1alpha1.Blueprint { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.BlueprintList, items []*v1alpha1.Blueprint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
