/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/component-operator/api/v1alpha1"
	corecssapcomv1alpha1 "github.com/sap/component-operator/pkg/client/clientset/versioned/typed/core.cs.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBlueprintVersions implements BlueprintVersionInterface
type fakeBlueprintVersions struct {
	*gentype.FakeClientWithList[*v1alpha1.BlueprintVersion, *v1alpha1.BlueprintVersionList]
	Fake *FakeCoreV1alpha1
}

func newFakeBlueprintVersions(fake *FakeCoreV1alpha1, namespace string) corecssapcomv1alpha1.BlueprintVersionInterface {
	return &fakeBlueprintVersions{
		gentype.NewFakeClientWithList[*v1alpha1.BlueprintVersion, *v1alpha1.BlueprintVersionList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("blueprintversions"),
			v1alpha1.SchemeGroupVersion.WithKind("BlueprintVersion"),
			func() *v1alpha1.BlueprintVersion { return &v1alpha1.BlueprintVersion{} },
			func() *v1alpha1.BlueprintVersionList { return &v1alpha1.BlueprintVersionList{} },
			func(dst, src *v1alpha1.BlueprintVersionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BlueprintVersionList) []*v1alpha1.BlueprintVersion {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.BlueprintVersionList, items []*v1alpha1.BlueprintVersion) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
