/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corecssapcomv1alpha1 "github.com/sap/component-operator/api/v1alpha1"
	scheme "github.com/sap/component-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BlueprintVersionsGetter has a method to return a BlueprintVersionInterface.
// A group's client should implement this interface.
type BlueprintVersionsGetter interface {
	BlueprintVersions(namespace string) BlueprintVersionInterface
}

// BlueprintVersionInterface has methods to work with BlueprintVersion resources.
type BlueprintVersionInterface interface {
	Create(ctx context.Context, blueprintVersion *corecssapcomv1alpha1.BlueprintVersion, opts v1.CreateOptions) (*corecssapcomv1alpha1.BlueprintVersion, error)
	Update(ctx context.Context, blueprintVersion *corecssapcomv1alpha1.BlueprintVersion, opts v1.UpdateOptions) (*corecssapcomv1alpha1.BlueprintVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corecssapcomv1alpha1.BlueprintVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*corecssapcomv1alpha1.BlueprintVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corecssapcomv1alpha1.BlueprintVersion, err error)
	BlueprintVersionExpansion
}

// blueprintVersions implements BlueprintVersionInterface
type blueprintVersions struct {
	*gentype.ClientWithList[*corecssapcomv1alpha1.BlueprintVersion, *corecssapcomv1alpha1.BlueprintVersionList]
}

// newBlueprintVersions returns a BlueprintVersions
func newBlueprintVersions(c *CoreV1alpha1Client, namespace string) *blueprintVersions {
	return &blueprintVersions{
		gentype.NewClientWithList[*corecssapcomv1alpha1.BlueprintVersion, *corecssapcomv1alpha1.BlueprintVersionList](
			"blueprintversions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corecssapcomv1alpha1.BlueprintVersion { return &corecssapcomv1alpha1.BlueprintVersion{} },
			func() *corecssapcomv1alpha1.BlueprintVersionList { return &corecssapcomv1alpha1.BlueprintVersionList{} },
		),
	}
}
