/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corecssapcomv1alpha1 "github.com/sap/component-operator/api/v1alpha1"
	scheme "github.com/sap/component-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BlueprintsGetter has a method to return a BlueprintInterface.
// A group's client should implement this interface.
type BlueprintsGetter interface {
	Blueprints(namespace string) BlueprintInterface
}

// BlueprintInterface has methods to work with Blueprint resources.
type BlueprintInterface interface {
	Create(ctx context.Context, blueprint *corecssapcomv1alpha1.Blueprint, opts v1.CreateOptions) (*corecssapcomv1alpha1.Blueprint, error)
	Update(ctx context.Context, blueprint *corecssapcomv1alpha1.Blueprint, opts v1.UpdateOptions) (*corecssapcomv1alpha1.Blueprint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corecssapcomv1alpha1.Blueprint, error)
	List(ctx context.Context, opts v1.ListOptions) (*corecssapcomv1alpha1.BlueprintList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corecssapcomv1alpha1.Blueprint, err error)
	BlueprintExpansion
}

// blueprints implements BlueprintInterface
type blueprints struct {
	*gentype.ClientWithList[*corecssapcomv1alpha1.Blueprint, *corecssapcomv1alpha1.BlueprintList]
}

// newBlueprints returns a Blueprints
func newBlueprints(c *CoreV1alpha1Client, namespace string) *blueprints {
	return &blueprints{
		gentype.NewClientWithList[*corecssapcomv1alpha1.Blueprint, *corecssapcomv1alpha1.BlueprintList](
			"blueprints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corecssapcomv1alpha1.Blueprint { return &corecssapcomv1alpha1.Blueprint{} },
			func() *corecssapcomv1alpha1.BlueprintList { return &corecssapcomv1alpha1.BlueprintList{} },
		),
	}
}
