/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and component-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/sap/component-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Blueprints returns a BlueprintInformer.
	Blueprints() TypedBlueprintInformer
	// BlueprintVersions returns a BlueprintVersionInformer.
	BlueprintVersions() TypedBlueprintVersionInformer
	// Components returns a ComponentInformer.
	Components() TypedComponentInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Blueprints returns a TypedBlueprintInformer.
func (v *version) Blueprints() TypedBlueprintInformer {
	return &blueprintInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// BlueprintVersions returns a TypedBlueprintVersionInformer.
func (v *version) BlueprintVersions() TypedBlueprintVersionInformer {
	return &blueprintVersionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Components returns a TypedComponentInformer.
func (v *version) Components() TypedComponentInformer {
	return &componentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
