name: Update generated artifacts

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Update generated artifacts
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Update generated artifacts
      run: |
        make generate
        make manifests
        go mod tidy

        git config user.name "${{ vars.WORKFLOW_USER_NAME }}"
        git config user.email "${{ vars.WORKFLOW_USER_EMAIL }}"
        git add -A
        git commit -m "Update generated artifacts"
        git push